local function make_deprecated_function_alias(old_funcname,new_funcname)
	load(old_funcname .. [[= function(...)
		return load("return ]] .. new_funcname .. [[(...)")(...)
	end]],"make_deprecated_function_alias")()
end
local function make_deprecated_function_no_replacement(old_funcname,message)
	load(old_funcname .. [[=
		(function()
			local oldfunc=]] .. old_funcname .. [[
			return function(...)
				Debug.PrintStacktrace()
				Debug.Message("]] .. old_funcname .. [[ is deprecated and will be removed. ]] .. message .. [[")
				return oldfunc(...)
			end
		end)()]],"make_deprecated_function_no_replacement")()
end

--Functions deprecated since version 41.0:
make_deprecated_function_no_replacement("Duel.GetEnvironment", "You should use Duel.IsEnvironment to check if a field spell is active on the field.")
make_deprecated_function_no_replacement("Duel.GetTributeCount", "You should use Duel.CheckTribute and relative functions to check if a monster can be tribute summoned.")
make_deprecated_function_alias("Auxiliary.selfbanishcost","Cost.SelfBanish")
make_deprecated_function_alias("Auxiliary.SelfBanishCost","Cost.SelfBanish")
make_deprecated_function_alias("Auxiliary.DiscardCost","Cost.Discard")
make_deprecated_function_alias("Auxiliary.dxmcostgen","Cost.DetachFromSelf")
make_deprecated_function_alias("Auxiliary.selfreleasecost","Cost.SelfRelease")
make_deprecated_function_alias("Auxiliary.SelfReleaseCost","Cost.SelfRelease")
make_deprecated_function_alias("Auxiliary.SelfTributeCost","Cost.SelfRelease")
make_deprecated_function_alias("Auxiliary.SelfToGraveCost","Cost.SelfToGrave")
make_deprecated_function_alias("Auxiliary.SelfToHandCost","Cost.SelfToHand")
make_deprecated_function_alias("Auxiliary.SelfToDeckCost","Cost.SelfToDeck")
make_deprecated_function_alias("Auxiliary.SelfToExtraCost","Cost.SelfToExtra")
make_deprecated_function_alias("Auxiliary.SelfDiscardCost","Cost.SelfDiscard")
make_deprecated_function_alias("Auxiliary.SelfDiscardToGraveCost","Cost.SelfDiscardToGrave")
make_deprecated_function_alias("Auxiliary.SelfRevealCost","Cost.SelfReveal")

--Functions deprecated since version 40.0:
make_deprecated_function_alias("Auxiliary.AskAny","Duel.AskAny")
make_deprecated_function_alias("Auxiliary.AskEveryone","Duel.AskEveryone")
make_deprecated_function_alias("Auxiliary.AnnounceAnotherAttribute","Duel.AnnounceAnotherAttribute")
make_deprecated_function_alias("Auxiliary.AnnounceAnotherRace","Duel.AnnounceAnotherRace")
make_deprecated_function_alias("Auxiliary.SelectEffect","Duel.SelectEffect")
make_deprecated_function_alias("Auxiliary.PlayFieldSpell","Duel.ActivateFieldSpell")
make_deprecated_function_alias("Auxiliary.CheckPendulumZones","Duel.CheckPendulumZones")
make_deprecated_function_alias("Auxiliary.nzatk","Card.HasNonZeroAttack")
make_deprecated_function_alias("Auxiliary.nzdef","Card.HasNonZeroDefense")
make_deprecated_function_alias("Auxiliary.disfilter1","Card.IsNegatableMonster")
make_deprecated_function_alias("Auxiliary.disfilter2","Card.IsNegatableSpellTrap")
make_deprecated_function_alias("Auxiliary.disfilter3","Card.IsNegatable")
make_deprecated_function_alias("Auxiliary.HasCounterListed","Card.ListsCounter")
make_deprecated_function_alias("Auxiliary.CanPlaceCounter","Card.PlacesCounter")
make_deprecated_function_alias("Auxiliary.EquipByEffectLimit","Card.EquipByEffectLimit")
make_deprecated_function_alias("Auxiliary.EquipByEffectAndLimitRegister","Card.EquipByEffectAndLimitRegister")
make_deprecated_function_alias("Auxiliary.IsMaterialListCode","Card.ListsCodeAsMaterial")
make_deprecated_function_alias("Auxiliary.IsMaterialListSetCard","Card.ListsArchetypeAsMaterial")
make_deprecated_function_alias("Auxiliary.IsArchetypeCodeListed","Card.ListsCodeWithArchetype")
make_deprecated_function_alias("Auxiliary.IsCodeListed","Card.ListsCode")
make_deprecated_function_alias("Auxiliary.IsCardTypeListed","Card.ListsCardType")
make_deprecated_function_alias("Auxiliary.HasListedSetCode","Card.ListsArchetype")
make_deprecated_function_alias("Auxiliary.IsGeminiState","Gemini.EffectStatusCondition")
make_deprecated_function_alias("Auxiliary.IsNotGeminiState","Auxiliary.NOT(Gemini.EffectStatusCondition)")
make_deprecated_function_alias("Auxiliary.GeminiNormalCondition","Gemini.NormalStatusCondition")
make_deprecated_function_alias("Auxiliary.EnableGeminiAttribute","Gemini.AddProcedure")
make_deprecated_function_alias("Auxiliary.EnableSpiritReturn","Spirit.AddProcedure")
make_deprecated_function_alias("Auxiliary.SpiritReturnReg","Spirit.SummonRegister")
make_deprecated_function_alias("Auxiliary.SpiritReturnOperation","Spirit.ReturnOperation")
make_deprecated_function_alias("Auxiliary.FilterFaceupFunction","Auxiliary.FaceupFilter")
make_deprecated_function_alias("Auxiliary.MZFilter","Card.IsInMainMZone")